name: Build macOS Client

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-13 # macos-13 is the last reliable Intel-based runner on GitHub

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update
        brew install raylib cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        # We explicitly search for homebrew libraries
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                 -DRAYLIB_ROOT="$(brew --prefix raylib)"

    - name: Build
      run: |
        cd build
        make client_gui

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: boats_client_macos_intel
        path: build/client_gui
